### ISSUE TITLE
Last test fail 

### ISSUE THREAD

**Issue by skamphax0r** [mjhea0/flaskr-tdd#18]
/home/skamphax0r/testing/flaskr-tdd/app.py:4: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy import SQLAlchemy
/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
..EEEE
======================================================================
ERROR: test_delete_message (__main__.FlaskrTestCase)
Ensure the messages are being deleted
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app-test.py", line 33, in setUp
    db.create_all()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 1007, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 999, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 941, in get_engine
    return connector.get_engine()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 533, in get_engine
    uri = self.get_uri()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 524, in get_uri
    return self._app.config['SQLALCHEMY_DATABASE_URI']
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.

======================================================================
ERROR: test_empty_db (__main__.FlaskrTestCase)
Ensure database is blank
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app-test.py", line 33, in setUp
    db.create_all()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 1007, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 999, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 941, in get_engine
    return connector.get_engine()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 533, in get_engine
    uri = self.get_uri()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 524, in get_uri
    return self._app.config['SQLALCHEMY_DATABASE_URI']
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.

======================================================================
ERROR: test_login_logout (__main__.FlaskrTestCase)
Test login and logout using helper functions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app-test.py", line 33, in setUp
    db.create_all()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 1007, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 999, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 941, in get_engine
    return connector.get_engine()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 533, in get_engine
    uri = self.get_uri()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 524, in get_uri
    return self._app.config['SQLALCHEMY_DATABASE_URI']
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.

======================================================================
ERROR: test_messages (__main__.FlaskrTestCase)
Ensure that user can post messages
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app-test.py", line 33, in setUp
    db.create_all()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 1007, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 999, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 941, in get_engine
    return connector.get_engine()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 533, in get_engine
    uri = self.get_uri()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 524, in get_uri
    return self._app.config['SQLALCHEMY_DATABASE_URI']
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/home/skamphax0r/flaskr-tdd/env/lib/python3.5/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.

----------------------------------------------------------------------
Ran 6 tests in 0.045s

FAILED (errors=4)

**Comment by mjhea0** [comment]
Can I see your code?

**Comment by skamphax0r** [comment]
It's the same as yours.

**Comment by skamphax0r** [comment]
What I should say is I cloned, and get the same errors.

**Comment by mjhea0** [comment]
I just tested it on my end and it works. Which version of Python are you using?

**Comment by skamphax0r** [comment]
Python 3.5.2+

click==6.7
Flask==0.12
Flask-SQLAlchemy==2.2
gunicorn==19.7.0
itsdangerous==0.24
Jinja2==2.9.5
MarkupSafe==1.0
SQLAlchemy==1.1.6
Werkzeug==0.11.15

**Comment by mjhea0** [comment]
It's because you are using Flask-SQLAlchemy version 2.2 and I am using version [2.1](https://github.com/mjhea0/flaskr-tdd/blob/master/requirements.txt#L2).

Remove:

```
pip uninstall flask-sqlalchemy
```

Add:

```
pip install flask-sqlalchemy==2.1
```

**Comment by mjhea0** [comment]
Update the tutorial: https://github.com/mjhea0/flaskr-tdd/blob/master/README.md#setup-sqlalchemy

Thanks!
